# Generated by Django 4.2.30 on 2026-08-28 12:47

from django.db import migrations, models
import django.db.models.deletion
import store.models
import store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم التطبيق')),
                ('short_description', models.CharField(blank=True, help_text='يظهر في بطاقة التطبيق داخل قائمة المتجر.', max_length=200, verbose_name='وصف مختصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=store.models.app_icon_upload_path, validators=[store.validators.MaxFileSizeValidator(5), store.validators.AllowedExtensionsValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='أيقونة التطبيق')),
                ('is_published', models.BooleanField(default=False, help_text='غير المنشور لا يظهر في المتجر العام.', verbose_name='منشور')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'تطبيق',
                'verbose_name_plural': 'التطبيقات',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store.models.app_screenshot_upload_path, validators=[store.validators.MaxFileSizeValidator(5), store.validators.AllowedExtensionsValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='تعليق')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='store.app', verbose_name='التطبيق')),
            ],
            options={
                'verbose_name': 'لقطة شاشة',
                'verbose_name_plural': 'لقطات الشاشة',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AppPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'أندرويد'), ('ios', 'آي أو إس'), ('windows', 'ويندوز'), ('macos', 'ماك أو إس')], max_length=20, verbose_name='المنصة')),
                ('store_url', models.URLField(blank=True, help_text='Google Play أو App Store.', max_length=500, verbose_name='رابط المتجر')),
                ('external_url', models.URLField(blank=True, help_text='رابط مباشر خارج الخادم.', max_length=500, verbose_name='رابط تنزيل خارجي')),
                ('file', models.FileField(blank=True, help_text='الامتدادات المسموحة تختلف حسب المنصة.', null=True, upload_to=store.models.app_package_upload_path, validators=[store.validators.MaxFileSizeValidator(500)], verbose_name='ملف التطبيق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='store.app', verbose_name='التطبيق')),
            ],
            options={
                'verbose_name': 'منصة تطبيق',
                'verbose_name_plural': 'منصات التطبيقات',
                'ordering': ['platform'],
            },
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['is_published'], name='store_app_published_idx'),
        ),
        migrations.AddConstraint(
            model_name='appplatform',
            constraint=models.UniqueConstraint(fields=('app', 'platform'), name='store_unique_app_platform'),
        ),
    ]
