# Generated by Django 6.0.4 on 2026-04-17 07:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='كم جنيهاً سودانياً يساوي الريال السعودي الواحد.', max_digits=10, verbose_name='سعر الصرف (جنيه/ريال)')),
                ('is_active', models.BooleanField(default=False, help_text='يجب أن يكون سعر واحد فقط نشطاً في أي وقت.', verbose_name='السعر الحالي')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضافه')),
            ],
            options={
                'verbose_name': 'سعر الصرف',
                'verbose_name_plural': 'أسعار الصرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='إجمالي المطلوب (ج.س)')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='يُحدَّث تلقائياً بواسطة Signal عند كل دفعة.', max_digits=12, verbose_name='إجمالي المدفوع (ج.س)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات مالية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_file', to='accounts.studentprofile', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ملف مالي',
                'verbose_name_plural': 'الملفات المالية',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sdg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ (جنيه سوداني)')),
                ('exchange_rate_at_payment', models.DecimalField(decimal_places=2, help_text='يُحفَظ تلقائياً من السعر النشط وقت الدفع. لا يجوز تعديله لضمان سلامة التقارير التاريخية.', max_digits=10, verbose_name='سعر الصرف لحظة الدفع (ج.س/ريال)')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي'), ('mobile_money', 'محفظة إلكترونية'), ('other', 'أخرى')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('receipt_number', models.CharField(blank=True, help_text='رقم تسلسلي للإيصال يُولَّد تلقائياً إن تُرِك فارغاً.', max_length=50, verbose_name='رقم الإيصال')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.financialfile', verbose_name='الملف المالي')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
