# Generated by Django 6.0.4 on 2026-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='رقم المعاملة/التحويل'),
        ),
    ]
