# Generated by Django 6.0.4 on 2026-04-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_bank_name_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender_account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم حساب المُرسل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
