# Generated by Django 6.0.4 on 2026-04-17 07:06

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='السكن')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'مشرفة',
                'verbose_name_plural': 'المشرفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_upload_path, verbose_name='الصورة الشخصية')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('teacher', 'أستاذ'), ('admin', 'مدير النظام'), ('manager', 'مدير')], default='student', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='طاقم العمل')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=150, verbose_name='اسم ولي الأمر')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='هاتف ولي الأمر')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='السكن / العنوان')),
                ('system_type', models.CharField(choices=[('online', 'أونلاين'), ('flash', 'فلاش')], default='online', max_length=10, verbose_name='نوع النظام')),
                ('device_id', models.CharField(blank=True, help_text='يُحفَظ تلقائياً عند أول दخول من تطبيق الموبايل. لا يُحرَّر إلا من قبل المدير.', max_length=255, null=True, unique=True, verbose_name='معرّف الجهاز')),
                ('device_bound_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ربط الجهاز')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('enrolled_grade', models.ForeignKey(blank=True, help_text='يُستخدم لفتح كورسات الفصل تلقائياً عند أول دفع (طلاب الأونلاين فقط).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='academic.grade', verbose_name='الفصل المسجّل فيه')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.supervisor', verbose_name='المشرفة')),
            ],
            options={
                'verbose_name': 'ملف الطالب',
                'verbose_name_plural': 'ملفات الطلاب',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='التخصص')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة مختصرة')),
                ('staff_type', models.CharField(choices=[('academic', 'هيئة تدريس'), ('administrative', 'هيئة إدارة')], default='academic', max_length=20, verbose_name='نوع الكادر')),
                ('is_public', models.BooleanField(default=False, verbose_name='ظاهر في صفحة الهبوط')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف الأستاذ',
                'verbose_name_plural': 'ملفات الأساتذة',
                'ordering': ['display_order', 'user__full_name'],
            },
        ),
    ]
