# Generated by Django 6.0.4 on 2026-04-17 16:06 (manually edited for data migration)

from django.db import migrations, models


def set_username_from_phone(apps, schema_editor):
    """
    لكل مستخدم موجود، نضع رقم هاتفه (phone) كـ username مؤقت.
    يجب تحديثها يدوياً من لوحة التحكم لاحقاً.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    seen = set()
    for user in CustomUser.objects.all():
        base = (user.phone or str(user.pk)[:8]).strip()
        candidate = base
        counter = 1
        while candidate in seen:
            candidate = f"{base}_{counter}"
            counter += 1
        seen.add(candidate)
        user.username = candidate
        user.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # 1. أضف الحقل بدون unique أولاً حتى نتمكن من ملئه
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                default='', max_length=150, unique=False,
                verbose_name='اسم المستخدم'
            ),
            preserve_default=False,
        ),
        # 2. اجعل كل username مشتقاً من phone (data migration)
        migrations.RunPython(set_username_from_phone, migrations.RunPython.noop),
        # 3. الآن أضف قيد الفرادة
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم'),
        ),
        # 4. اجعل phone اختيارياً
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
