# Generated by Django 6.0.4 on 2026-04-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='السكن / العنوان'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف ولي الأمر'),
        ),
    ]
