# Generated by Django 6.0.4 on 2026-04-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='اسم الطالب')),
                ('system_type', models.CharField(help_text='مثال: سوداني، IGCSE، أمريكي...', max_length=100, verbose_name='نوع النظام الدراسي')),
                ('guardian_name', models.CharField(max_length=150, verbose_name='اسم ولي الأمر')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='هاتف ولي الأمر')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('closed', 'مكتمل / مغلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'طلب تسجيل طالب',
                'verbose_name_plural': 'طلبات تسجيل الطلاب',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
