# Generated by Django 6.0.4 on 2026-05-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='level',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('intermediate', 'متوسط'), ('secondary', 'ثانوي')], max_length=20, verbose_name='المرحلة الدراسية'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=50, verbose_name='السنة الدراسية'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='system_type',
            field=models.CharField(choices=[('online', 'أونلاين'), ('flash', 'فلاش كورس')], default='online', max_length=20, verbose_name='نوع النظام الدراسي'),
        ),
    ]
