# Generated by Django 6.0.4 on 2026-05-22 16:04

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentrequest_level_studentrequest_year_of_study_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('content', models.TextField(help_text='نص الشرط أو التعليمات. يمكن استخدام عدة أسطر.', verbose_name='المحتوى')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'شرط تسجيل',
                'verbose_name_plural': 'شروط التسجيل',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='device_type',
            field=models.CharField(blank=True, help_text='نوع جهاز الموبايل (يُحفَظ تلقائياً عند الربط).', max_length=100, null=True, verbose_name='نوع الجهاز'),
        ),
        migrations.CreateModel(
            name='NewStudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل للطالب')),
                ('national_id', models.CharField(max_length=50, verbose_name='الرقم الوطني للطالب')),
                ('level', models.CharField(choices=[('primary', 'ابتدائي'), ('middle', 'متوسط'), ('secondary', 'ثانوي')], max_length=20, verbose_name='المرحلة الدراسية')),
                ('grade', models.CharField(choices=[('first', 'الأول'), ('second', 'الثاني'), ('third', 'الثالث'), ('fourth', 'الرابع'), ('fifth', 'الخامس'), ('sixth', 'السادس')], max_length=20, verbose_name='الصف الدراسي')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('student_status', models.CharField(choices=[('returning', 'معيد في نفس السنة'), ('new_year', 'عام دراسي جديد')], max_length=20, verbose_name='حالة الطالب')),
                ('has_siblings', models.BooleanField(default=False, verbose_name='هل لديه أشقاء في مدرسة نمبر ون؟')),
                ('siblings_info', models.JSONField(blank=True, default=list, help_text='قائمة بأسماء وصفوف الأشقاء [{name, grade}, ...]', verbose_name='بيانات الأشقاء')),
                ('residence', models.CharField(max_length=300, verbose_name='مكان إقامة الطالب الحالي')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ ميلاد الطالب')),
                ('student_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم هاتف الطالب')),
                ('academic_result_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.registration_upload_path, verbose_name='صورة آخر نتيجة دراسية')),
                ('birth_certificate_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.registration_upload_path, verbose_name='صورة شهادة الميلاد')),
                ('personal_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.registration_upload_path, verbose_name='صورة شخصية / جواز')),
                ('father_id_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.registration_upload_path, verbose_name='صورة بطاقة الأب')),
                ('mother_id_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.registration_upload_path, verbose_name='صورة بطاقة الأم')),
                ('payment_receipt_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.registration_upload_path, verbose_name='صورة إيصال الدفع')),
                ('guardian_name', models.CharField(max_length=200, verbose_name='اسم ولي أمر الطالب')),
                ('guardian_phone', models.CharField(max_length=20, verbose_name='رقم هاتف ولي الأمر')),
                ('guardian_residence', models.CharField(max_length=300, verbose_name='مكان إقامة ولي الأمر')),
                ('mother_full_name', models.CharField(max_length=200, verbose_name='اسم الأم الكامل')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('reviewed', 'تمت المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='new', max_length=20, verbose_name='حالة الطلب')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_registrations', to='accounts.supervisor', verbose_name='المشرفة')),
            ],
            options={
                'verbose_name': 'طلب تسجيل جديد',
                'verbose_name_plural': 'طلبات التسجيل الجديدة',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
