# Generated by Django 4.2.30 on 2026-05-26 21:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_registrationcondition_studentprofile_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudentregistration',
            name='student_id_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.registration_upload_path, verbose_name='  تحميل الرقم الوطني للطالب '),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='academic_result_image',
            field=models.ImageField(upload_to=accounts.models.registration_upload_path, verbose_name=' تحميل اخر نتيجة دراسية للطالب '),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='admin_notes',
            field=models.TextField(verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='birth_certificate_image',
            field=models.ImageField(upload_to=accounts.models.registration_upload_path, verbose_name='   تحميل شهادة ميلاد الطالب'),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='father_id_image',
            field=models.ImageField(upload_to=accounts.models.registration_upload_path, verbose_name='  تحميل الرقم الوطني للأب '),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='mother_id_image',
            field=models.ImageField(upload_to=accounts.models.registration_upload_path, verbose_name='  تحميل الرقم الوطني للأم'),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='payment_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.registration_upload_path, verbose_name='  تحميل اشعار سداد الرسوم / اشعار بنكك '),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='personal_photo',
            field=models.ImageField(upload_to=accounts.models.registration_upload_path, verbose_name='   صورة شخصية للطالب / باسبورت'),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='submitted_at',
            field=models.DateTimeField(verbose_name='تاريخ الإرسال'),
        ),
    ]
