# Generated by Django 4.2.30 on 2026-05-26 21:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_newstudentregistration_student_id_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentregistration',
            name='student_id_image',
            field=models.ImageField(upload_to=accounts.models.registration_upload_path, verbose_name='  تحميل الرقم الوطني للطالب '),
        ),
    ]
