# Generated by Django 4.2.30 on 2026-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_newstudentregistration_student_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentregistration',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
    ]
