# Generated by Django 4.2.30 on 2026-05-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_course_system_type_grade_system_type_and_more'),
        ('accounts', '0009_alter_newstudentregistration_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentregistration',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.grade', verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='newstudentregistration',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.level', verbose_name='المرحلة الدراسية'),
        ),
    ]
