# Generated by Django 4.2.30 on 2026-05-30 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_course_system_type_grade_system_type_and_more'),
        ('accounts', '0010_alter_newstudentregistration_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'أستاذ'), ('admin', 'مدير النظام'), ('manager', 'مدير'), ('lecture_supervisor', 'مشرف محاضرات')], default='student', max_length=20, verbose_name='الدور'),
        ),
        migrations.CreateModel(
            name='LectureSupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('assigned_courses', models.ManyToManyField(blank=True, help_text='الكورسات التي يملك هذا المشرف صلاحية إدارة محاضراتها.', related_name='lecture_supervisors', to='academic.course', verbose_name='الكورسات المخصصة')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'lecture_supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_supervisor_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشرف محاضرات',
                'verbose_name_plural': 'مشرفو المحاضرات',
                'ordering': ['-created_at'],
            },
        ),
    ]
