# Generated by Django 4.2.30 on 2026-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_role_lecturesupervisorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturesupervisorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'مشرف الكورسات', 'verbose_name_plural': 'مشرفو الكورسات'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'أستاذ'), ('admin', 'مدير النظام'), ('manager', 'مدير'), ('lecture_supervisor', 'مشرف الكورسات')], default='student', max_length=20, verbose_name='الدور'),
        ),
    ]
