# Generated by Django 4.2.30 on 2026-09-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_lecturesupervisorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentregistration',
            name='student_status',
            field=models.CharField(choices=[('returning', 'عائد لنفس السنه'), ('new_year', 'عام دراسي جديد')], max_length=20, verbose_name='حالة الطالب'),
        ),
    ]
