# Generated by Django 6.0.4 on 2026-04-30 05:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=False, verbose_name='النسخ التلقائي مفعّل')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='weekly', max_length=10, verbose_name='التكرار')),
                ('keep_last_n', models.PositiveIntegerField(default=5, verbose_name='الاحتفاظ بآخر')),
                ('last_auto_backup_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر نسخ تلقائي')),
            ],
            options={
                'verbose_name': 'إعدادات النسخ الاحتياطي',
                'verbose_name_plural': 'إعدادات النسخ الاحتياطي',
            },
        ),
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('backup_type', models.CharField(choices=[('full', 'كامل (قاعدة بيانات + ملفات)'), ('db_only', 'قاعدة البيانات فقط'), ('media_only', 'الملفات المرفوعة فقط')], default='full', max_length=20, verbose_name='نوع النسخة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم ملف النسخة')),
                ('restored_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الاستعادة')),
                ('status', models.CharField(choices=[('success', 'ناجحة'), ('failed', 'فاشلة')], default='success', max_length=10, verbose_name='الحالة')),
                ('log_text', models.TextField(blank=True, verbose_name='سجل التفاصيل')),
                ('backup_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_logs', to='backups.backupfile', verbose_name='النسخة الاحتياطية')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores_performed', to=settings.AUTH_USER_MODEL, verbose_name='استعادها')),
            ],
            options={
                'verbose_name': 'سجل استعادة',
                'verbose_name_plural': 'سجلات الاستعادة',
                'ordering': ['-restored_at'],
            },
        ),
    ]
