# Generated by Django 6.0.4 on 2026-04-29 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_course_system_type_grade_system_type_and_more'),
        ('accounts', '0004_studentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الاختبار')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة الاختبار (بالدقائق)')),
                ('passing_score', models.FloatField(default=50.0, help_text='الدرجة المطلوبة للنجاح من إجمالي درجات الاختبار.', verbose_name='درجة النجاح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.course', verbose_name='الكورس')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'اختبار',
                'verbose_name_plural': 'الاختبارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='الدرجة المحققة')),
                ('percentage', models.FloatField(default=0, verbose_name='النسبة المئوية')),
                ('is_passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التسليم')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='الاختبار')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='accounts.studentprofile', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'محاولة اختبار',
                'verbose_name_plural': 'محاولات الاختبارات',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('true_false', 'صح / خطأ'), ('multiple_choice', 'اختيار من متعدد'), ('fill_blank', 'أكمل الفراغ'), ('matching', 'مطابقة')], default='multiple_choice', max_length=20, verbose_name='نوع السؤال')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('marks', models.FloatField(default=1.0, verbose_name='الدرجة')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('correct_answer', models.JSONField(default=dict, help_text='تُخزَّن بصيغة JSON حسب نوع السؤال.', verbose_name='الإجابة الصحيحة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='الاختبار')),
            ],
            options={
                'verbose_name': 'سؤال اختبار',
                'verbose_name_plural': 'أسئلة الاختبارات',
                'ordering': ['exam', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='نص الخيار')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.examquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'خيار سؤال',
                'verbose_name_plural': 'خيارات الأسئلة',
                'ordering': ['question', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.JSONField(default=dict, verbose_name='إجابة الطالب')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحيحة')),
                ('earned_marks', models.FloatField(default=0, verbose_name='الدرجة المكتسبة')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt', verbose_name='المحاولة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='exams.examquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة محاولة',
                'verbose_name_plural': 'إجابات المحاولات',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
