# Generated by Django 6.0.4 on 2026-05-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='title',
            field=models.CharField(blank=True, default='', help_text='عنوان وصفي مختصر لتمييز السؤال بسرعة (اختياري).', max_length=255, verbose_name='عنوان السؤال'),
        ),
    ]
