# Generated by Django 6.0.4 on 2026-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة اختيارية مرفقة بالسؤال (للمطابقة وأكمل الفراغ).', null=True, upload_to='exams/questions/', verbose_name='صورة السؤال'),
        ),
    ]
