# Generated by Django 6.0.4 on 2026-04-17 07:06

import academic.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='نص الخيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='هو الإجابة الصحيحة')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'خيار',
                'verbose_name_plural': 'الخيارات',
                'ordering': ['question', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الكورس')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='صورة مصغّرة')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'كورس',
                'verbose_name_plural': 'الكورسات',
                'ordering': ['grade', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان التمرين')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات التمرين')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='0 = بلا حدود', verbose_name='الحد الأقصى للمحاولات')),
                ('pass_percentage', models.PositiveSmallIntegerField(default=60, verbose_name='نسبة النجاح (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تمرين',
                'verbose_name_plural': 'التمارين',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفصل')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['level', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المحاضرة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('youtube_url', models.URLField(blank=True, help_text='يُمرَّر عبر iframe مع ?modestbranding=1&rel=0 في الواجهة.', verbose_name='رابط يوتيوب')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=academic.models.lesson_pdf_upload_path, verbose_name='ملف PDF')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0, help_text='المدة التقريبية للمحاضرة بالدقائق.', verbose_name='المدة (دقيقة)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محاضرة',
                'verbose_name_plural': 'المحاضرات',
                'ordering': ['unit', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='آخر مشاهدة')),
            ],
            options={
                'verbose_name': 'تقدم المحاضرة',
                'verbose_name_plural': 'تقدم المحاضرات',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المرحلة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مرحلة',
                'verbose_name_plural': 'المراحل',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('marks', models.FloatField(default=1.0, verbose_name='الدرجة')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/questions/', verbose_name='صورة السؤال')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['exercise', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ منح الوصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وصول كورس',
                'verbose_name_plural': 'وصول الكورسات',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='الدرجة المحققة')),
                ('percentage', models.FloatField(default=0, verbose_name='النسبة المئوية')),
                ('is_passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='رقم المحاولة')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسليم')),
            ],
            options={
                'verbose_name': 'تسليم',
                'verbose_name_plural': 'التسليمات',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'إجابة تسليم',
                'verbose_name_plural': 'إجابات التسليمات',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الوحدة')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['course', 'display_order'],
            },
        ),
    ]
