# Generated by Django 6.0.4 on 2026-04-17 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='الأستاذ المسؤول'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.grade', verbose_name='الفصل'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='academic.lesson', verbose_name='المحاضرة'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='academic.lesson', verbose_name='المحاضرة'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='accounts.studentprofile', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.level', verbose_name='المرحلة'),
        ),
        migrations.AddField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academic.exercise', verbose_name='التمرين'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='academic.question', verbose_name='السؤال'),
        ),
        migrations.AddField(
            model_name='studentcourseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_accesses', to='academic.course', verbose_name='الكورس'),
        ),
        migrations.AddField(
            model_name='studentcourseaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='فارغ إذا كان تلقائياً عبر الدفع.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='مُنِح بواسطة'),
        ),
        migrations.AddField(
            model_name='studentcourseaccess',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to='accounts.studentprofile', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='submission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academic.exercise', verbose_name='التمرين'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.studentprofile', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_answers', to='academic.question', verbose_name='السؤال'),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_answers', to='academic.choice', verbose_name='الخيار المختار'),
        ),
        migrations.AddField(
            model_name='submissionanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='academic.submission', verbose_name='التسليم'),
        ),
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academic.course', verbose_name='الكورس'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academic.unit', verbose_name='الوحدة'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('student', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseaccess',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='submissionanswer',
            unique_together={('submission', 'question')},
        ),
    ]
