# Generated by Django 6.0.4 on 2026-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='system_type',
            field=models.CharField(choices=[('online', 'أونلاين'), ('flash', 'فلاش')], default='online', max_length=10, verbose_name='نوع النظام'),
        ),
        migrations.AddField(
            model_name='grade',
            name='system_type',
            field=models.CharField(choices=[('online', 'أونلاين'), ('flash', 'فلاش')], default='online', max_length=10, verbose_name='نوع النظام'),
        ),
        migrations.AddField(
            model_name='level',
            name='system_type',
            field=models.CharField(choices=[('online', 'أونلاين'), ('flash', 'فلاش')], default='online', max_length=10, verbose_name='نوع النظام'),
        ),
    ]
