# Generated by Django 4.2.30 on 2026-07-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_lesson_live_podcast_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='live_podcast_title',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='live_podcast_url',
        ),
        migrations.AddField(
            model_name='course',
            name='live_podcast_title',
            field=models.CharField(blank=True, default='', help_text='اسم الجلسة المباشرة — يُعرَض للطلاب في التطبيق.', max_length=255, null=True, verbose_name='عنوان البودكاست المباشر'),
        ),
        migrations.AddField(
            model_name='course',
            name='live_podcast_url',
            field=models.URLField(blank=True, default='', help_text='رابط Zoom أو أي منصة مباشرة. يفتح التطبيق المتصفح مباشرةً.', null=True, verbose_name='رابط البودكاست المباشر'),
        ),
    ]
