# Generated by Django 4.2.30 on 2026-07-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_lesson_live_podcast_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='live_podcast_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='live_podcast_url',
        ),
    ]
