# Generated by Django 4.2.30 on 2026-07-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150, verbose_name='اسم الغرفة')),
                ('room_type', models.CharField(choices=[('online', 'أونلاين'), ('flash', 'فلاش')], default='online', help_text='يُحدد أي الطلاب يرون هذه الغرفة: أونلاين أم فلاش.', max_length=10, verbose_name='نوع النظام')),
                ('course_type', models.CharField(choices=[('scientific', 'علمي'), ('literary', 'أدبي'), ('general', 'عام')], default='general', help_text='معلومة تنظيمية للمسؤول — لا تؤثر في فلترة الطلاب.', max_length=20, verbose_name='نوع الكورس')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'غرفة بث',
                'verbose_name_plural': 'غرف البث',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200, verbose_name='اسم الجلسة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('provider', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('teams', 'Microsoft Teams'), ('youtube', 'YouTube Live'), ('other', 'أخرى')], default='zoom', max_length=20, verbose_name='مزود البث')),
                ('stream_url', models.URLField(help_text='رابط Zoom / Google Meet / YouTube أو أي منصة بث.', verbose_name='رابط البث')),
                ('scheduled_start', models.DateTimeField(verbose_name='موعد البداية')),
                ('scheduled_end', models.DateTimeField(verbose_name='موعد النهاية')),
                ('status', models.CharField(choices=[('upcoming', 'قادمة'), ('live', 'مباشرة الآن'), ('ended', 'انتهت'), ('archived', 'مؤرشفة')], default='upcoming', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='live.liveroom', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'جلسة بث',
                'verbose_name_plural': 'جلسات البث',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.AddIndex(
            model_name='liveroom',
            index=models.Index(fields=['room_type'], name='liveroom_room_type_idx'),
        ),
        migrations.AddIndex(
            model_name='liveroom',
            index=models.Index(fields=['is_active'], name='liveroom_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='liveroom',
            index=models.Index(fields=['room_type', 'is_active'], name='liveroom_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status'], name='livesession_status_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['room'], name='livesession_room_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['scheduled_start'], name='livesession_start_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['room', 'status'], name='livesession_room_status_idx'),
        ),
    ]
