# Generated by Django 4.2.30 on 2026-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد النهاية'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد البداية'),
        ),
    ]
