# Generated by Django 4.2.30 on 2026-09-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_remove_live_podcast_fields'),
        ('live', '0002_make_dates_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['-created_at'], 'verbose_name': 'جلسة بث', 'verbose_name_plural': 'جلسات البث'},
        ),
        migrations.RemoveIndex(
            model_name='livesession',
            name='livesession_start_idx',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='scheduled_start',
        ),
        migrations.AddField(
            model_name='liveroom',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='الطلاب المسجّلون في هذا الفصل وحدهم يرون الغرفة. فارغ = كل فصول النظام.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_rooms', to='academic.grade', verbose_name='الفصل الدراسي'),
        ),
        migrations.AddIndex(
            model_name='liveroom',
            index=models.Index(fields=['grade'], name='liveroom_grade_idx'),
        ),
    ]
