# Generated by Django 4.2.30 on 2026-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_room_grade_and_drop_session_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveroom',
            options={'ordering': ['display_order', 'room_name'], 'verbose_name': 'غرفة بث', 'verbose_name_plural': 'غرف البث'},
        ),
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['room', 'display_order', 'session_name'], 'verbose_name': 'جلسة بث', 'verbose_name_plural': 'جلسات البث'},
        ),
        migrations.AddField(
            model_name='liveroom',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
    ]
