# Generated by Django 4.2.30 on 2026-09-14 08:57

from django.db import migrations, models


def number_existing(apps, schema_editor):
    """
    ترقيم مميّز لكل ما هو قائم قبل فرض قيد التفرّد.

    كل الغرف والجلسات على صفر بعد 0004، وقيد التفرّد يرفض ذلك. تُرقَّم
    بترتيب الإنشاء تصاعدياً — الأقدم 1 والأحدث N — فمع «الأعلى أولاً»
    يعود الشكل الذي عرفه المدير قبل الترتيب اليدوي: الأحدث في الأعلى.
    ما رقّمه المدير يدوياً بعد 0004 (غير صفر) يُترك، ويُرقَّم الباقي فوقه.
    """
    LiveRoom    = apps.get_model("live", "LiveRoom")
    LiveSession = apps.get_model("live", "LiveSession")

    def renumber(qs):
        top = qs.exclude(display_order=0).order_by("-display_order")                 .values_list("display_order", flat=True).first() or 0
        for obj in qs.filter(display_order=0).order_by("created_at", "id"):
            top += 1
            obj.display_order = top
            obj.save(update_fields=["display_order"])

    renumber(LiveRoom.objects.all())
    for room_id in LiveSession.objects.values_list("room_id", flat=True).distinct():
        renumber(LiveSession.objects.filter(room_id=room_id))


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_display_order'),
    ]

    operations = [
        migrations.RunPython(number_existing, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='liveroom',
            options={'ordering': ['-display_order', 'room_name'], 'verbose_name': 'غرفة بث', 'verbose_name_plural': 'غرف البث'},
        ),
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['room', '-display_order', 'session_name'], 'verbose_name': 'جلسة بث', 'verbose_name_plural': 'جلسات البث'},
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='الأعلى يظهر أولاً. اتركه فارغاً ليأخذ الأعلى تلقائياً.', null=True, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='الأعلى يظهر أولاً. اتركه فارغاً ليأخذ الأعلى تلقائياً.', null=True, verbose_name='ترتيب العرض'),
        ),
        migrations.AddConstraint(
            model_name='liveroom',
            constraint=models.UniqueConstraint(fields=('display_order',), name='liveroom_display_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.UniqueConstraint(fields=('room', 'display_order'), name='livesession_room_order_unique'),
        ),
    ]
