# Generated by Django 4.2.30 on 2026-09-14 08:57

from django.db import migrations, models


def number_existing(apps, schema_editor):
    """
    ترقيم مميّز لكل ما هو قائم قبل فرض قيد التفرّد.

    كل صفٍّ يُعاد ترقيمه لا الأصفار وحدها: بعد 0004 كانت القيمة الافتراضية
    صفراً، لكن المدير كان قد رقّم بعض الغرف يدوياً عبر واجهة #10 التي لم
    تفرض تفرّداً، فوُجدت في الإنتاج قيمٌ غير صفرية مكرّرة (رقمان 1 مثلاً)
    والترقيم السابق كان يتخطّاها فيسقط القيد.

    يُحفَظ الترتيب المرئي الأخير: واجهة #10 كانت تصاعدية
    (display_order ثم الاسم)، و#11 تنازلية. فنرتّب كما كان يراه المدير
    تصاعدياً، ونُسند N للأول و1 للأخير، فيبقى الأول أولاً تحت التنازلي.
    النتيجة تسلسل كثيف فريد 1..N بلا فجوات ولا تكرار.
    """
    LiveRoom    = apps.get_model("live", "LiveRoom")
    LiveSession = apps.get_model("live", "LiveSession")

    def renumber(rows):
        # لا قيد تفرّد بعدُ عند تنفيذ RunPython، فالتكرار اللحظي أثناء
        # الحلقة غير مهم؛ الحالة النهائية وحدها تُحسب.
        n = len(rows)
        for i, obj in enumerate(rows):
            obj.display_order = n - i
            obj.save(update_fields=["display_order"])

    renumber(list(LiveRoom.objects.order_by("display_order", "room_name", "id")))
    for room_id in LiveSession.objects.values_list("room_id", flat=True).distinct():
        renumber(list(
            LiveSession.objects
            .filter(room_id=room_id)
            .order_by("display_order", "session_name", "id")
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_display_order'),
    ]

    operations = [
        migrations.RunPython(number_existing, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='liveroom',
            options={'ordering': ['-display_order', 'room_name'], 'verbose_name': 'غرفة بث', 'verbose_name_plural': 'غرف البث'},
        ),
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['room', '-display_order', 'session_name'], 'verbose_name': 'جلسة بث', 'verbose_name_plural': 'جلسات البث'},
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='الأعلى يظهر أولاً. اتركه فارغاً ليأخذ الأعلى تلقائياً.', null=True, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='الأعلى يظهر أولاً. اتركه فارغاً ليأخذ الأعلى تلقائياً.', null=True, verbose_name='ترتيب العرض'),
        ),
        migrations.AddConstraint(
            model_name='liveroom',
            constraint=models.UniqueConstraint(fields=('display_order',), name='liveroom_display_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.UniqueConstraint(fields=('room', 'display_order'), name='livesession_room_order_unique'),
        ),
    ]
