# Generated by Django 4.2.30 on 2026-09-14 08:57

from django.db import migrations


def number_existing(apps, schema_editor):
    """
    ترقيم مميّز لكل ما هو قائم قبل فرض قيد التفرّد.

    كل صفٍّ يُعاد ترقيمه لا الأصفار وحدها: بعد 0004 كانت القيمة الافتراضية
    صفراً، لكن المدير كان قد رقّم بعض الغرف يدوياً عبر واجهة #10 التي لم
    تفرض تفرّداً، فوُجدت في الإنتاج قيمٌ غير صفرية مكرّرة (رقمان 1 مثلاً)
    والترقيم السابق كان يتخطّاها فيسقط القيد.

    يُحفَظ الترتيب المرئي الأخير: واجهة #10 كانت تصاعدية
    (display_order ثم الاسم)، و#11 تنازلية. فنرتّب كما كان يراه المدير
    تصاعدياً، ونُسند N للأول و1 للأخير، فيبقى الأول أولاً تحت التنازلي.
    النتيجة تسلسل كثيف فريد 1..N بلا فجوات ولا تكرار.

    هذه الهجرة بيانات فقط، منفصلة عن هجرة المخطّط (0006). السبب أن
    PostgreSQL يرفض ALTER TABLE داخل معاملة تحمل أحداث triggers مؤجّلة من
    تحديثات سابقة ("pending trigger events")؛ ففصلُ التحديثات في هجرة تُثبَّت
    قبل هجرة المخطّط يُفرّغ تلك الأحداث أولاً. (SQLite لا يفرض هذا فلم يظهر
    محلياً.)
    """
    LiveRoom    = apps.get_model("live", "LiveRoom")
    LiveSession = apps.get_model("live", "LiveSession")

    def renumber(rows):
        # لا قيد تفرّد بعدُ عند تنفيذ RunPython، فالتكرار اللحظي أثناء
        # الحلقة غير مهم؛ الحالة النهائية وحدها تُحسب.
        n = len(rows)
        for i, obj in enumerate(rows):
            obj.display_order = n - i
            obj.save(update_fields=["display_order"])

    renumber(list(LiveRoom.objects.order_by("display_order", "room_name", "id")))
    for room_id in LiveSession.objects.values_list("room_id", flat=True).distinct():
        renumber(list(
            LiveSession.objects
            .filter(room_id=room_id)
            .order_by("display_order", "session_name", "id")
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_display_order'),
    ]

    operations = [
        migrations.RunPython(number_existing, migrations.RunPython.noop),
    ]
