# Generated by Django 4.2.30 on 2026-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    تغييرات المخطّط لترتيب البث، منفصلة عن ترقيم البيانات في 0005.

    الفصل ضروري على PostgreSQL: تحديثات الترقيم في 0005 تُخلّف أحداث triggers
    مؤجّلة، وALTER TABLE لا يُنفَّذ داخل معاملة تحملها. تثبيت 0005 أولاً يُفرّغ
    تلك الأحداث، فتعمل عمليات المخطّط هنا في معاملة نظيفة.
    """

    dependencies = [
        ('live', '0005_order_unique_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveroom',
            options={'ordering': ['-display_order', 'room_name'], 'verbose_name': 'غرفة بث', 'verbose_name_plural': 'غرف البث'},
        ),
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['room', '-display_order', 'session_name'], 'verbose_name': 'جلسة بث', 'verbose_name_plural': 'جلسات البث'},
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='الأعلى يظهر أولاً. اتركه فارغاً ليأخذ الأعلى تلقائياً.', null=True, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='الأعلى يظهر أولاً. اتركه فارغاً ليأخذ الأعلى تلقائياً.', null=True, verbose_name='ترتيب العرض'),
        ),
        migrations.AddConstraint(
            model_name='liveroom',
            constraint=models.UniqueConstraint(fields=('display_order',), name='liveroom_display_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.UniqueConstraint(fields=('room', 'display_order'), name='livesession_room_order_unique'),
        ),
    ]
