# Generated by Django 6.0.4 on 2026-04-17 07:06

import django.db.models.deletion
import site_settings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('body', models.TextField(blank=True, verbose_name='نص الإعلان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=site_settings.models.announcement_image_upload_path, verbose_name='صورة الإعلان')),
                ('link', models.URLField(blank=True, verbose_name='رابط اختياري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط (ظاهر في الـ Slider)')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العرض')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('whatsapp', 'واتساب'), ('telegram', 'تيليغرام'), ('facebook', 'فيسبوك'), ('instagram', 'إنستغرام'), ('twitter', 'إكس (تويتر)'), ('youtube', 'يوتيوب'), ('phone', 'هاتف'), ('email', 'بريد إلكتروني'), ('website', 'موقع إلكتروني'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الأداة')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='التسمية')),
                ('value', models.CharField(help_text='مثال: https://wa.me/xxxx أو +249xxxxxxxxx', max_length=500, verbose_name='الرابط أو الرقم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'أداة تواصل',
                'verbose_name_plural': 'أدوات التواصل',
                'ordering': ['display_order', 'tool_type'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='مدارس ومعاهد نمبر ون', max_length=200, verbose_name='اسم المؤسسة')),
                ('short_title', models.CharField(blank=True, help_text='يظهر أسفل الاسم في قسم الـ Hero.', max_length=300, verbose_name='العنوان المختصر (Tagline)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=site_settings.models.site_logo_upload_path, verbose_name='الشعار')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/', verbose_name='الأيقونة (Favicon)')),
                ('vision', models.TextField(blank=True, verbose_name='الرؤية')),
                ('mission', models.TextField(blank=True, verbose_name='الرسالة')),
                ('objectives', models.TextField(blank=True, help_text='يمكن استخدام فواصل السطر لتحديد الأهداف.', verbose_name='الأهداف')),
                ('history', models.TextField(blank=True, verbose_name='التاريخ / القصة')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='وصف الـ Meta (SEO)')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='كلمات الـ Meta (SEO)')),
                ('primary_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني الرئيسي')),
                ('primary_phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف الرئيسي')),
                ('address_text', models.CharField(blank=True, max_length=300, verbose_name='العنوان التفصيلي')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150, verbose_name='اسم المُرسِل')),
                ('sender_phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('unread', 'جديد / غير مقروء'), ('seen', 'تمت المشاهدة'), ('contacted', 'تم التواصل'), ('pending', 'معلق')], default='unread', max_length=15, verbose_name='الحالة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاستلام')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_messages', to=settings.AUTH_USER_MODEL, verbose_name='تولّى المعالجة')),
            ],
            options={
                'verbose_name': 'رسالة واردة',
                'verbose_name_plural': 'صندوق الوارد',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='المسمى الوظيفي')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=site_settings.models.staff_card_photo_upload_path, verbose_name='الصورة')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة مختصرة')),
                ('card_type', models.CharField(choices=[('academic', 'هيئة تدريس'), ('administrative', 'هيئة إدارة')], default='academic', max_length=20, verbose_name='نوع الكادر')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر في صفحة الهبوط')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('teacher_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_card', to='accounts.teacherprofile', verbose_name='ملف الأستاذ (اختياري)')),
            ],
            options={
                'verbose_name': 'بطاقة كادر',
                'verbose_name_plural': 'بطاقات الكادر',
                'ordering': ['card_type', 'display_order', 'name'],
            },
        ),
    ]
