# Generated by Django 4.2.30 on 2026-09-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lecture', 'محاضرة جديدة'), ('exam', 'امتحان جديد'), ('result', 'نتيجة امتحان'), ('live_session', 'جلسة بث مباشر'), ('live_podcast', 'بث مباشر'), ('announcement', 'إعلان هام')], default='announcement', max_length=50),
        ),
    ]
